### ISSUE TITLE
Allow changing settings of an instance

### ISSUE THREAD

**Issue by timsanwald** [cloudamqp/terraform-provider-cloudamqp#124]
It would be great to be able to set the configuration of an instance as described in the [API](https://docs.cloudamqp.com/cloudamqp_api.html#rabbitmq-configuration)

Use Case:
* Enabling prometheus per queue metrics after enabling the plugin via terraform.

**Comment by tbroden84** [comment]
The configuration in our API for Prometheus have been deprecated. Since RabbitMQ 3.8.0, there is support for multiple prometheus endpoints to allow more specific metrics. 

There are three different endpoints available for prometheus metrics

- _/metrics_ aggregated metrics
- _/metrics/per-object_ unaggregated metrics, so you see metrics per object in RabbitMQ
- _/metrics/detailed_ to specify which metrics to get.

More information here: [https://www.cloudamqp.com/blog/Prometheus-and-Grafana.html ](https://www.cloudamqp.com/blog/Prometheus-and-Grafana.html) and here: https://www.rabbitmq.com/prometheus.html
