### ISSUE TITLE
Initial setup instructions improvements

### ISSUE THREAD

**Issue by klloveall** [cloudamqp/terraform-provider-cloudamqp#25]
Hi y'all!

Super excited to be able to control this under Terraform, but I ran into a couple issues while trying to set this up that I wanted to make y'all aware of.

1. This might be an issue with dep instead of y'all, but in order to get it to work (after using their quick-install script thing), I had to add `~/go/bin` to my $PATH in order for `dep` to be found.
2. In order to make `make depupdate` work, I had to `touch ~/go/src/github.com/cloudamqp/terraform-provider/Gopkg.lock`.
3. In order to make `make init` work, I had to `mkdir ~/go/src/github.com/cloudamqp/terraform-provider/bin/`.

Overall, I'm super excited for this, but I wanted to make y'all aware of these issues that a total newcomer (both to this package and go as a whole) ran into.

**Comment by tbroden84** [comment]
Glad you are exited and thanks for the input. Will look over the readme and add necessary information.

**Comment by cruzzan** [comment]
I think this issue can be closed, point 2 and 3 should have been fixed by https://github.com/cloudamqp/terraform-provider-cloudamqp/pull/27 

And as mentioned the problem with dep is that the binary is installed in `$GOPATH/bin` and thus that directory needs to be on the users path. This is also mentioned in the official install instructions: https://golang.org/doc/install#install

@klloveall @tbroden84
