### ISSUE TITLE
Feature: upgrade RabbitMQ to specific version

### ISSUE THREAD

**Issue by dentarg** [cloudamqp/terraform-provider-cloudamqp#293]
The `cloudamqp_upgrade_rabbitmq` resource only allows you to update your cluster to the latest versions (Erlang, RabbitMQ) available. This is a moving target. Some users want to control the exact version used.

We have the following API endpoint for this: https://docs.cloudamqp.com/cloudamqp_api.html#upgrade-rabbitmq

**Comment by tbroden84** [comment]
Released new version [v1.31.0](https://github.com/cloudamqp/terraform-provider-cloudamqp/releases/tag/v1.31.0). Makes it possible to specify the version while using `cloudamqp_upgrade_rabbitmq`. Still have its limits due to iterated upgrades made be needed to get newer Erlang version. 

Also a good step before trying this out from `cloudamqp_instance` once we upgrade to Terraform Framework.
