### ISSUE TITLE
make install gives errors

### ISSUE THREAD

**Issue by farooqdevops** [cloudamqp/terraform-provider-cloudamqp#52]
Following your mentioned instructions, when i try to install terraform provider  using make install, i get following error:

$:~/go/src/github.com/cloudamqp/terraform-provider-cloudamqp$ make install
rm -f ~/.terraform.d/plugins/terraform-provider-cloudamqp*
linux

GOOS=linux GOARCH= go build -ldflags "-X 'github.com/cloudamqp/terraform-provider-cloudamqp/cloudamqp.version=1.6.0'" -o terraform-provider-cloudamqp_v1.6.0
$# github.com/cloudamqp/terraform-provider-cloudamqp/cloudamqp
cloudamqp/data_source_nodes.go:65:18: api.ReadNodes undefined (type *api.API has no field or method ReadNodes)
Makefile:79: recipe for target 'build' failed
make: *** [build] Error 2

Can you assist how to properly use this, better if i can install it and run only one terraform plan apply instead of plan and apply separately for this module.

**Comment by tbroden84** [comment]
My bad, didn't push the update for our API wrapper. Have now pushed out the updates and updated the version.

**Comment by farooqdevops** [comment]
thanks, now it works.

**Comment by tbroden84** [comment]
I usually just go over these points if I want to install the provider. 
1. Run `make install`. Once the provider is built it will be moved to ~/.terraform.d/plugins.
2. Run `terraform init`, from the folder where your .tf file is located. This will initialize all necessary providers. 
2. Run `terraform apply`. I never use plan anymore, since if there is no execution plan it will be created by apply before prompting for execution (not sure if this is the correct way, but works for my purpose). 

Also there is the comman line flag -auto-approve, to automatically approve the apply. But haven't tried it out myself.

**Comment by farooqdevops** [comment]
thanks again :-)
