### ISSUE TITLE
Applying firewall rules silently fails on 1.7.2

### ISSUE THREAD

**Issue by GenPage** [cloudamqp/terraform-provider-cloudamqp#66]
Upon updating to 1.7.2, I've found that the provider no longer applies the firewall rules properly.

Our integration tests picked up the issue first:
```
Failures:
  1) integration-f1a541c809 should have firewall rules
     Failure/Error: expect(INSTANCE.get_firewall_rules().length).to be > 1
       expected: > 1
            got:   0
     # ./spec/test_rabbitmq_spec.rb:24:in `block (2 levels) in <top (required)>'
Finished in 2.34 seconds (files took 3.22 seconds to load)
17 examples, 1 failure
```

Upon further investigation, I see the rules being applied in the terraform plan:
```
  # cloudamqp_security_firewall.vpn_firewall_rules will be created
  + resource "cloudamqp_security_firewall" "vpn_firewall_rules" {
      + id          = (known after apply)
      + instance_id = (known after apply)

      + rules {
          + ip       = "10.148.184.0/22"
          + ports    = []
          + services = [
              + "AMQP",
              + "AMQPS",
            ]
        }
      + rules {
          + ip       = "10.20.0.0/22"
          + ports    = []
          + services = [
              + "AMQP",
              + "AMQPS",
            ]
        }
    }
```

and the plan completes successfully:
```
Apply complete! Resources: 39 added, 0 changed, 0 destroyed.
Releasing state lock. This may take a few moments...
```

But when viewing in the UI, there are no rules actually set:
![Screen Shot 2020-06-25 at 2 02 18 PM](https://user-images.githubusercontent.com/3201853/85774059-7df58180-b6ec-11ea-9050-b3415af418a5.png)

I see in the terraform log output it does try to create (i've attached the full trace log):
```
2020-06-25T13:50:30.298-0400 [DEBUG] plugin.terraform-provider-cloudamqp_v1.7.2: 2020/06/25 13:50:30 [DEBUG] cloudamqp::resource::security_firewall::create localFirewalls: [map[description: ip:10.148.184.0/22 ports:[] services:[AMQP AMQPS]] map[description: ip:10.20.0.0/22 ports:[] services:[AMQP AMQPS]]]
2020-06-25T13:50:30.298-0400 [DEBUG] plugin.terraform-provider-cloudamqp_v1.7.2: 2020/06/25 13:50:30 [DEBUG] cloudamqp::resource::security_firewall::create instance id: 103002
2020-06-25T13:50:30.298-0400 [DEBUG] plugin.terraform-provider-cloudamqp_v1.7.2: 2020/06/25 13:50:30 [DEBUG] go-api::security_firewall::create instance ID: 103002, params: [map[description: ip:10.148.184.0/22 ports:[] services:[AMQP AMQPS]] map[description: ip:10.20.0.0/22 ports:[] services:[AMQP AMQPS]]]
```

I believe this is due to changes somehow here:
https://github.com/cloudamqp/terraform-provider-cloudamqp/commit/14fb8cc38810b1cd5ae6e65aec88f604b529f70a#diff-e2dfb2fcb91664f42948f7e5571ef45e

Thank you for your help and assistance! :)

[firewall_issue.log](https://github.com/cloudamqp/terraform-provider-cloudamqp/files/4833081/firewall_issue.log)

**Comment by tbroden84** [comment]
Seems to be two different issues
1. Read cannot validate new data against old data. Therefore interpret everything as null and force new rules. 
2. Create or update doesn't reflect the rules in backend. 

Will download 1.6.0 and see if it is also there. Hard to see the issue is just renaming. In never version we also introduced reading the state from backend after applying create and update. If read fails from the beginning it could mess things up.

**Comment by tbroden84** [comment]
Think I manage to narrow down the issues. At least what I have seen during my testing and troubleshooting.

1. After 1.6.0 there was an additional argument introduced 'description', set as optional. Since rules is an array/TypeSet it seems to not be very keen on having missmatch in optional arguments. For example, imported the default rule to the state. When adding the info to the tf-file, I left out description. This triggered a missmatch between new data and old and a new rule was forced to be created.

```
resource "cloudamqp_security_firewall" "firewall" {
  instance_id = cloudamqp_instance.instance.id
  rules {
    ip = "0.0.0.0/0"
    ports = []
    services = ["STOMP", "AMQP", "MQTTS", "STOMPS", "MQTT", "AMQPS"]
  }
```

When adding description to the tf-file, there was no problem. So somehow there is an issue using array/TypeSet and not populating optional arguments that in the backend have data.

```
resource "cloudamqp_security_firewall" "firewall" {
  instance_id = cloudamqp_instance.instance.id
  rules {
    description = "Default"
    ip = "0.0.0.0/0"
    ports = []
    services = ["STOMP", "AMQP", "MQTTS", "STOMPS", "MQTT", "AMQPS"]
  }
```

2. Found some new updates in our underlying APIs. Now we use a cache on the firewall information, to lessen the requests to the cloud provider. Every time the rules are create or updated, it uses a delay of 10 seconds, meanwhile the cache is invalidated before the rules are added. This should affect both TF and our console. Would need to add a wait until the rules and cache have finished.

Did you try to reload the console/security page after a while? For me the new rules appeared after waiting for about 10+ s and then reload.

**Comment by tbroden84** [comment]
See if this solves issue 2. Added a delay in our golang API wrapper, that waits 20 seconds before retrieving the firewall rules after changing them. Due to the fact that our API uses internal cache with the firewall rules. They are invalidated on each create, update or delete call with a 10 seconds delay. 

Went over your logs and compared them against ours. The only thing I found was the request with an empty response, about 2 seconds after a create call. Which should be inline with the track about cache invalidation as the issue,

Please let me know if you can run it as it or if I need to create a new release.

**Comment by andrewthetechie** [comment]
@tbroden84 I'm following up on troubleshooting this issue from @GenPage. I'll work on testing this and get back to you

**Comment by adityabyreddy74** [comment]
Facing the same issue (#2) i.e. rules are not being persisted during transactions. Using provider version : 1.8

**Comment by tbroden84** [comment]
@adityabyreddy74 Have been having a problem interpret the response from our backend and how TF interpret the information. Rules is of type, TypeSet with both required and optional attributes. Now I can just forward the information from the backend. The downside is that all information must be intact regardless of optional attributes. 

Found this affected by the default firewall rule, which have description = "Default" information.
```
 rules {
    description = "Default"
    ip = "0.0.0.0/0"
    ports = []
    services = ["STOMP", "AMQP", "MQTTS", "STOMPS", "MQTT", "AMQPS"]
  }
```

From my experience this is needed to avoid TF to recreate all rules. But have a plan on how to fix this.

**Comment by dentarg** [comment]
@andrewthetechie @sig-abyreddy @GenPage do you still have issues with firewall rules?

**Comment by andrewthetechie** [comment]
We have moved on from using CloudAMQP to AWS Rabbitmq and no longer have a cloudamqp cluster to test this on

**Comment by dentarg** [comment]
If anyone has any firewall problem (or any other problem), please open a new issue!
