### ISSUE TITLE
Invite to publish to the Terraform Registry

### ISSUE THREAD

**Issue by aicarmic** [cloudamqp/terraform-provider-cloudamqp#78]
👋  Hi there! We noticed this provider is on our list of community providers, however it has not yet been published to the newly-released Terraform Registry for Providers (registry.terraform.io). We'd like to invite you to get it published, since it makes using and installing it much easier for anyone using Terraform 0.13! Instructions for doing so are available [here](https://www.terraform.io/docs/registry/providers/publishing.html). If you need some help producing documentation, take a look at [this project](https://github.com/hashicorp/terraform-plugin-docs) which may come in handy!

Please note that we will soon be redirecting the [community listing page](https://www.terraform.io/docs/providers/type/community-index.html) to registry.terraform.io.

Thanks for your contributions and we look forward to seeing this provider listed soon!

Thanks,
Team Terraform @ HashiCorp

**Comment by tbroden84** [comment]
Hi, thanks for reaching out. 

Yes have been in contact with you to start the process about two weeks ago. However been on semi sick leave and focus elsewhere. Earlier this summer we got accepted to the old Terraform Provider Development Program. From there we forked a new repository, under your namespace. As I understand we will now keep this repository as official. Then only need to upload our signed binaries during publish through Github Actions to Terraform registry? 

Furthermore we will be looking to have our provider verified by you/Hashicorp. Saw there was additional steps in order to do that. 

For now started from where I finished last and setting up GitHub action release.

**Comment by aicarmic** [comment]
Hi @tbroden84 sure that sounds good! Hope you're in good health. For joining our partner verified program, you can check out this guide for more info: https://www.terraform.io/guides/terraform-provider-development-program.html

**Comment by tbroden84** [comment]
Hi @aicarmic. Thanks, unfortunately got worse so been away on full sick leave. On recovery now, but manage to get help of my co-workers. So we will start taking a look at this again.

**Comment by tbroden84** [comment]
Looks like we succeeded to get Github action working. https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest

Since we now have two repositories, our own and the one you created before. We wonder if we can keep our own as official. Now there is a split on issues created in both repositories.

**Comment by aicarmic** [comment]
@tbroden84 That's great news! On the one residing in `terraform-providers` we will mark it as Archived with a note pointing to this one. We can also set a flag on the registry itself so that users with the old one get automatically redirected to source from the new provider location. Does that work?

**Comment by aicarmic** [comment]
@tbroden84 we've gone ahead and archived the old repo, and set the moved_to parameter. Let us know if we can do anything else to help and thanks for your contributions!

**Comment by tbroden84** [comment]
@aicarmic Thanks. Sounds good.
