### ISSUE TITLE
Allow managing Erlang version

### ISSUE THREAD

**Issue by yashbhutwala** [cloudamqp/terraform-provider-cloudamqp#83]
Currently erlang version cannot be set, updated, managed with this terraform provider.

Migrated from https://github.com/hashicorp/terraform-provider-cloudamqp/issues/3 and relates to #82

**Comment by tbroden84** [comment]
Have had internal discussion about this, to automate the upgrade of both RMQ and Erlang versions. So far only prototype solutions but no real one found.  One way could be to allow the updates to occur similar as our console, but also have its risks.

**Comment by yashbhutwala** [comment]
Thanks @tbroden84 for keeping in the loop!  As a SaaS user, ultimately rabbitmq version is the only one I care about, erlang version is more or less an implementation detail to me;  not sure if that helps in assessing the risks and making the right tradeoffs.

**Comment by tbroden84** [comment]
@yashbhutwala Ok, thanks for your inputs. Also been receiving more and more requests on being able to upgrade. Unfortunately if RMQ version can be allowed to be upgraded. We also need to allow upgrade Erlang version. Since each RMQ version have a min/max required Erlang version. More information can be found here: https://www.rabbitmq.com/which-erlang.html 

We solved it for the console by locking certain versions, and force the user to do the necessary upgrades before moving forward. Hence why we in the long run, would like to have this automated so you as a user could just pick a RMQ version.

**Comment by tbroden84** [comment]
We have now released a new version [v1.17.0](https://github.com/cloudamqp/terraform-provider-cloudamqp/releases/tag/v1.17.0) and added support to automatically upgrade both RabbitMQ and Erlang versions to latest possible upgradable versions.

Reason both are upgraded in the same go, is to avoid mismatch in required Erlang version depending on RabbitMQ version. From current versions used, it's possible to check which possible versions the upgrade will upgrade to.

* As data source [cloudamqp_upgradable_versions](https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest/docs/data-sources/upgradable_versions)
* From our backend [API](https://docs.cloudamqp.com/cloudamqp_api.html#fetch-what-versions-rabbitmq-erlang-upgrade-will-upgrade-to)

Then to actually trigger the upgrade

* From resource [cloudamqp_upgrade_rabbitmq](https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest/docs/resources/upgrade_rabbitmq)

Note: Depending on current versions used, `cloudamqp_upgrade_rabbitmq` may need to be triggered multiple times. 

Pull request for this feature [#151](https://github.com/cloudamqp/terraform-provider-cloudamqp/pull/151)
