### ISSUE TITLE
Bug: not setting initial rmq_version does not work

### ISSUE THREAD

**Issue by yashbhutwala** [cloudamqp/terraform-provider-cloudamqp#84]
Even though `rmq_version` is not supposed to be managed by terraform if unset and it is listed as **optional** from the provider docs: https://www.terraform.io/docs/providers/cloudamqp/r/instance.htmlhttps://www.terraform.io/docs/providers/cloudamqp/r/instance.html, cloudamq instance creation fails with this error:

`Error: CreateInstance failed, status: 422, message: map[error:RabbitMQ version is not valid. Supported version 3.6.16 3.7.6 3.7.7 3.7.8 3.7.9 3.7.10 3.7.11 3.7.12 3.7.13 3.7.14 3.7.15 3.7.16 3.7.17 3.7.18 3.7.19 3.7.20 3.7.21 3.7.22 3.7.23 3.7.24 3.7.25 3.7.26 3.7.27 3.7.28 3.8.0 3.8.1 3.8.2 3.8.3 3.8.4 3.8.5 3.8.6 3.8.7 3.8.8 3.8.9]`

NOTE: while running apply for an already provisioned cloudamqp while setting rmq_version does run successfully; however, it does not manage it as raised by Enhancement Request: #82 

Migrated from https://github.com/hashicorp/terraform-provider-cloudamqp/issues/6 since that repository is archived now.

**Comment by tbroden84** [comment]
@yashbhutwala Thanks for reporting this. When not declaring RMQ version, the current version used by CloudAMQP should be fetched from our APIs. But apparently this does work. Will create a task to look into this.

**Comment by tbroden84** [comment]
@yashbhutwala Corrected so that the default value used by CloudAMQP API is fetched. Also played around with computed and/or optional and think I find the correct behaviour. When both using computed and optional, it's possible to initial set a version. If left out, it will instead be seen as computed and use the default value. Next 'terraform apply' will then act as computed and the attribute read from the state file. 

Will make a release a bit later today.

**Comment by yashbhutwala** [comment]
Awesome!!  Thanks @tbroden84 🙏 💯

**Comment by tbroden84** [comment]
@yashbhutwala Did some cleanup today and have made a new release v1.8.5. Contains the updates for handling this issue.

**Comment by yashbhutwala** [comment]
Thanks @tbroden84!  I will update and verify the change once I can.
