### ISSUE TITLE
Include rabbitmq's internal host as part of instance create resource attributes

### ISSUE THREAD

**Issue by sig-abyreddy** [cloudamqp/terraform-provider-cloudamqp#92]
Cloudamqp has changed the domains for accessing instances. Earlier it used to be <hostname>.rmq.cloudamqp.com as an external domain for the instance. Now it has changed to <hostname>.rmq2.cloudamqp.com . Its the same change with internal host of the instance. It's hard to track how this domain is being managed and when this gets a change. 

Can we have an attribute to read internal host with response to cloudamqp instance creation resource i.e. https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest/docs/resources/instance ?

Or at least with instance data source i.e. https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest/docs/data-sources/instance

**Comment by tbroden84** [comment]
@sig-abyreddy 

Answer here too. ​Correct the new instances will have *.rmq2.cloudamqp.com and *.in.rmq2.cloudamqp.com. Yes can add this information.

**Comment by sig-abyreddy** [comment]
Thanks @tbroden84

**Comment by juanma-cvega** [comment]
Hi, is there any ETA for this issue to be implemented? 
My use case, currently I have 3 different servers deployed using the old format (*.rmq.cloudamqp.com for the public host and *.in.cloudamqp.com for the private one). I used to do some string replacement in Terraform given the internal host name is not exposed. Now that doesn't work as the internal host name contains *.in.rmq2.cloudamqp.com and I cannot maintain logic for 2 different types of string replacements. 
Besides, I'm securing access to the cluster by configuring the firewall to only allow access from private VPC CIDR ranges. Some weeks ago, after creating a VPC peering to the cluster, host name lookups were resolving the cluster private IPs. Today, new deployments always return the public IPs so I don't know if there has been a network change no your side.

**Comment by 8102** [comment]
Hey @dentarg.
Was the fix introduce in [v.1.12.0](https://github.com/cloudamqp/terraform-provider-cloudamqp/releases/tag/v1.12.0) release or was it done on the API side?
I'm asking because in my use case, even when using an older version (i.e.: [v.1.11.0](https://github.com/cloudamqp/terraform-provider-cloudamqp/releases/tag/v1.11.0)) I'm getting the internal host where I used to get the external one before.

My use case is similar as follow:
```tf
resource "cloudamqp_instance" "instance" {
  name        = "My Supper Dupper Instance"
  plan        = "rabbit"
  region      = "amazon-web-services::eu-west-1"
  nodes       = 1
  rmq_version = "3.8.3"
  vpc_subnet  = "10.56.72.0/2"
}

data "cloudamqp_credentials" "credentials" {
  depends_on  = [cloudamqp_instance.instance]
  instance_id = cloudamqp_instance.instance.id
}

provider "rabbitmq" {
  endpoint = "https://${cloudamqp_instance.instance.host}"
  username = data.cloudamqp_credentials.credentials.username
  password = data.cloudamqp_credentials.credentials.password
}
```

This is perfectly working with old instances using the old `*.rmq.cloudamqp.com` domain, but when it's an instance using the new domain `*.rmq2.cloudamqp.com` the domain of `cloudamqp_instance.instance.host` is now the internal one.

In the meantime I'm doing something like this to "fix" this "problem" (it works with both `rmq` and `rmq2`):
```hcl
provider "rabbitmq" {
  endpoint = "https://${replace(cloudamqp_instance.instance.host, ".in", "")}"
  username = data.cloudamqp_credentials.credentials.username
  password = data.cloudamqp_credentials.credentials.password
}
```


So finally, Is there a way for us to retrieve both the internal and external host from the `cloudamqp_instance` resource?

**Comment by dentarg** [comment]
The fix was done in the backend API.

There's no way to retrieve both from the API today.

We will look into this again.

**Comment by 8102** [comment]
Clear, thanks for having a look!
